### ISSUE TITLE
Failed to load resource: net::ERR_INVALID_RESPONSE service-worker.js

### ISSUE THREAD

**Issue by Gukulkan** [Saka7/spring-boot-angular4-boilerplate#4]
After all steps on index page can see
A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE 
:4200/service-worker.js 

And the page is blank.

**Comment by neskartu** [comment]
Same here.

**Comment by Saka7** [comment]
Following template doesn't have any UI-related stuff (to let it stay versatile and unopinionated). So, the page should be blank.

As for `service-workers`(SW) - they actually don't work in development mode. I'll try to figure it out, but you don't really need `SW` when developing an application. In production-built app `SW` works as they should.
